[2024-07-04T13:29:13.310+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-04T13:29:13.320+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_transformation_v1.transform_data scheduled__2024-07-03T00:00:00+00:00 [queued]>
[2024-07-04T13:29:13.328+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_transformation_v1.transform_data scheduled__2024-07-03T00:00:00+00:00 [queued]>
[2024-07-04T13:29:13.328+0530] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-04T13:29:13.345+0530] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2024-07-03 00:00:00+00:00
[2024-07-04T13:29:13.347+0530] {standard_task_runner.py:63} INFO - Started process 95852 to run task
[2024-07-04T13:29:13.351+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_transformation_v1', 'transform_data', 'scheduled__2024-07-03T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp82vre6ta']
[2024-07-04T13:29:13.353+0530] {standard_task_runner.py:91} INFO - Job 15: Subtask transform_data
[2024-07-04T13:29:13.385+0530] {task_command.py:426} INFO - Running <TaskInstance: data_transformation_v1.transform_data scheduled__2024-07-03T00:00:00+00:00 [running]> on host ongraph-Lenovo-V130-14IKB
[2024-07-04T13:29:13.437+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rohit' AIRFLOW_CTX_DAG_ID='data_transformation_v1' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-03T00:00:00+00:00'
[2024-07-04T13:29:13.438+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-04T13:29:13.472+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-04T13:29:13.473+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ongraph/Desktop/airflow/airflow_ETL/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ongraph/Desktop/airflow/airflow_ETL/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ongraph/Desktop/airflow/airflow_ETL/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ongraph/Desktop/airflow/airflow_ETL/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/ongraph/Desktop/airflow/airflow_ETL/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ongraph/Desktop/airflow/airflow_ETL/dags/etl.py", line 11, in data_transformation
    df = pd.DataFrame(raw_data)
NameError: name 'pd' is not defined
[2024-07-04T13:29:13.478+0530] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=data_transformation_v1, task_id=transform_data, run_id=scheduled__2024-07-03T00:00:00+00:00, execution_date=20240703T000000, start_date=20240704T075913, end_date=20240704T075913
[2024-07-04T13:29:13.487+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task transform_data (name 'pd' is not defined; 95852)
[2024-07-04T13:29:13.523+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-04T13:29:13.548+0530] {logging_mixin.py:188} WARNING - /home/ongraph/Desktop/airflow/airflow_ETL/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class SqliteOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.)
[2024-07-04T13:29:13.564+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-04T13:29:13.569+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
